#!/bin/bash

#SBATCH --job-name=fit_psych
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=00:15:00
 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Antonio Fernandez

# make output directory
mkdir -p out_dir

# run the actual python code
singularity exec docker://brainlife/dipy:1.1.1 python3 main.py